version: "3.8"

services:
  db:
    image: postgres:latest # последняя версия postgresql образа
    container_name: tm_database # название контейнера
    hostname: ${DB_HOSTNAME}
    environment:
      POSTGRES_DB:       ${DB_NAME}            # название БД
      POSTGRES_USER:     ${DB_USERNAME}          # имя пользователя
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # пароль пользователя
    ports:
      - "${DB_PORT}:5432" # порт деплоя
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Для постоянного хранения данных
  
  traffic_manager:
    image: python:3.10-slim  # Use the official Python image
    working_dir: /app
    volumes:
      - ./flask-app:/app  # Mount your Flask app directory
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python app.py"
    ports:
      - "5000:5000"



volumes:
  postgres_data:  # Определение тома для хранения данных