version: "3.8"

services:
  db:
    image: postgres:latest # последняя версия postgresql образа
    container_name: postgres_flask # название контейнера
    hostname: ${DB_HOSTNAME}
    environment:
      POSTGRES_DB:       ${DB_NAME}            # название БД
      POSTGRES_USER:     ${DB_USERNAME}          # имя пользователя
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # пароль пользователя
    ports:
      - "${DB_PORT}:5432" # порт деплоя
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Для постоянного хранения данных

volumes:
  postgres_data:  # Определение тома для хранения данных