#!/bin/bash

./tests/routes/alert_settings
./tests/routes/alerts
./tests/routes/device_types
./tests/routes/events
./tests/routes/logs
./tests/routes/metrics
./tests/routes/network_nodes
./tests/routes/regions
./tests/routes/sessions
./tests/routes/traffic_statictics
./tests/routes/users