#!/bin/bash

# TODO вставить ENVIRONMENT вместо var
url="localhost:5000"

# /device_types
request_device_types="$url/device_types"                 # Ссылка запроса
response_device_types=$(curl -s "$request_device_types") # Присваивание ответа от сервера переменной

if [ "$response_device_types" = "all device types" ]; then
    echo -e "\033[32mTEST 1 PASSED!
    $request_device_types -> $response_device_types
    \033[0m"
else
    echo -e "\033[31mTEST 1 FAILED!
        $request_device_types -> $response_device_types
    \033[0m"
fi


# /device_types?id=####
device_type_id="1231"                                              # id настройки алерта
request_device_type_id="$url/device_types?id=$device_type_id"      # Ссылка запроса
response_device_type_id=$(curl -s "$request_device_type_id")       # Присваивание ответа от сервера переменной

# ожидаемый ответ запроса
expected="device type with $device_type_id id"

echo "TEST 2 $request_device_type_id"

if [ "$response_device_type_id" = "$expected" ]; then
    echo -e "\033[32mPASSED!
    $request_device_type_id -> $response_device_type_id
    \033[0m"
else
    echo -e "\033[31mFAILED!
        got      $request_device_type_id -> $response_device_type_id
    \033[0m"
fi