#!/bin/bash

# TODO вставить ENVIRONMENT вместо var
url="localhost:5000"

# /logs
request_logs="$url/logs"                 # Ссылка запроса
response_logs=$(curl -s "$request_logs") # Присваивание ответа от сервера переменной

if [ "$response_logs" = "all logs" ]; then
    echo -e "\033[32mTEST 1 PASSED!
    $request_logs -> $response_logs
    \033[0m"
else
    echo -e "\033[31mTEST 1 FAILED!
        $request_logs -> $response_logs
    \033[0m"
fi


# /logs?id=####
log_id="1231"                                        # id настройки алерта
request_log_id="$url/logs?id=$log_id"            # Ссылка запроса
response_log_id=$(curl -s "$request_log_id")       # Присваивание ответа от сервера переменной

# ожидаемый ответ запроса
expected="log with $log_id id"

echo "TEST 2 $request_log_id"

if [ "$response_log_id" = "$expected" ]; then
    echo -e "\033[32mPASSED!
    $request_log_id -> $response_log_id
    \033[0m"
else
    echo -e "\033[31mFAILED!
        got      $request_log_id -> $response_log_id
    \033[0m"
fi