#!/bin/bash

# TODO вставить ENVIRONMENT вместо var
url="localhost:5000"

# /sessions
request_sessions="$url/sessions"                 # Ссылка запроса
response_sessions=$(curl -s "$request_sessions") # Присваивание ответа от сервера переменной

if [ "$response_sessions" = "all sessions" ]; then
    echo -e "\033[32mTEST 1 PASSED!
    $request_sessions -> $response_sessions
    \033[0m"
else
    echo -e "\033[31mTEST 1 FAILED!
        $request_sessions -> $response_sessions
    \033[0m"
fi


# /sessions?id=####
session_id="1231"                                        # id настройки алерта
request_session_id="$url/sessions?id=$session_id"            # Ссылка запроса
response_session_id=$(curl -s "$request_session_id")       # Присваивание ответа от сервера переменной

# ожидаемый ответ запроса
expected="session with $session_id id"

echo "TEST 2 $request_session_id"

if [ "$response_session_id" = "$expected" ]; then
    echo -e "\033[32mPASSED!
    $request_session_id -> $response_session_id
    \033[0m"
else
    echo -e "\033[31mFAILED!
        got      $request_session_id -> $response_session_id
    \033[0m"
fi